### ISSUE TITLE
how to save data in vram

### ISSUE THREAD

**Issue by bylijian** [liquidapps-io/zeus-coldtoken-sample#2]
Hi，I read the code ,but it seem a common contract without use vram. Maybe I make a mistake,but could you show me the code to store data in vram?

**Comment by tmuskal** [comment]
Hi,
We tried to make the use of vRAM as transparent as possible from a developer's perspective:

The "accounts" table is using **dapp::multi_index** (which uses the vRAM mechanism behind the scenes) rather than the **eosio::multi_index** 

Also, the macros used in the example make your contract "DAPP-Services compatible", which support the vRAM mechanism through DSPs (please refer to the whitepaper at https://www.liquidapps.io for more details)

**Comment by tmuskal** [comment]
more implementation details can be found here: 
https://github.com/liquidapps-io/dapp-service-ipfs

and

https://github.com/liquidapps-io/zeus-dapp-network
